# Generated by Django 3.2 on 2023-01-31 16:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True,
                help_text='Напишите биографию пользователя',
                null=True,
                verbose_name='Биография пользователя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                db_index=True,
                help_text='Укажите email пользователя',
                max_length=254,
                unique=True,
                verbose_name='Email пользователя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'user'),
                    ('admin', 'admin'),
                    ('moderator', 'moderator'),
                ],
                default='user',
                help_text='Укажите роль пользователя',
                max_length=15,
                verbose_name='Роль пользователя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={
                    'unique': 'A user with that username already exists.'
                },
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                ],
                verbose_name='username',
            ),
        ),
    ]
